name: 02 - Workflow Events
on:
  push:
  pull_request:
  workflow_dispatch:
  #schedule:
     #- cron: '1 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Trigger event is: ${{ github.event_name }} in ${{ github.workflow }} workflow"
