name: 05 - 2 - Event Filters and Activity Types 
on: 
  workflow_dispatch:
  #pull_request:
  #  branches: [main]
  #  types: [closed]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Build PR 
        run: |
          echo "Running whenever a PR is closed"
